In [1]:
using Symbolics
using RuntimeGeneratedFunctions
RuntimeGeneratedFunctions.init(@__MODULE__)

In [2]:
_prod(a, b, c, arrs...) = a .* _prod(b, c, arrs...)
_prod(a, b) = a .* b
_prod(a) = a

" makes polynomial combinations of basis "
function hamiltonian_poly(z, order, inds...)
    ham = []

    if order == 0
        Num(1)
    elseif order == length(inds)
        ham = vcat(ham, _prod([z[i] for i in inds]...))
    else
        start_ind = length(inds) == 0 ? 1 : inds[end]
        for j in start_ind:length(z)
            ham = vcat(ham, hamiltonian_poly(z, order, inds..., j))
        end
    end

    return ham
end

hamiltonian_poly

In [ ]:
" collects and sums only polynomial combinations of basis "
function hamiltonian(z, a, order)
    ham = []

    for i in 1:order
        ham = vcat(ham, hamiltonian_poly(z, i))
    end

    sum(collect(a .* ham))
end

In [ ]:
" collects and sums polynomial and trigonometric combinations of basis "
function hamil_trig(z, a, order, trig_wave_num)
    ham = []

    # Polynomial basis
    for i in 1:order
        ham = vcat(ham, hamiltonian_poly(z, i))
    end

    # Trigonometric basis
    for k = 1:trig_wave_num
        ham = vcat(ham, vcat(sin.(k*z)), vcat(cos.(k*z)))
    end

    ham = sum(collect(a .* ham))

    return ham

end

In [ ]:

" collects and sums polynomial, trigonometric, and states differences combinations of basis "
function hamiltonian_two(z, a, order, trig_wave_num, diffs_power, trig_state_diffs, exp_diff)
    ham = []

    # Polynomial basis
    for i in 1:order
        ham = vcat(ham, hamiltonian_poly(z, i))
    end

    # Trigonometric basis
    for k = 1:trig_wave_num
        ham = vcat(ham, vcat(sin.(k*z)), vcat(cos.(k*z)))
    end

    # For States difference power basis, trigonometric or exponential power states difference basis
    if diffs_power != 0 || trig_state_diffs != 0 || exp_diff != 0
        diffs = Vector{Symbolics.Num}()
        idx = 1
        for i in eachindex(z)
            for j in eachindex(z)
                if i == j
                    continue  # skip index where difference is between same state
                end
                push!(diffs, (z[i] - z[j]))
                idx += 1
            end
        end
    end
        
    if diffs_power > 0
        for k = 1:diffs_power
            ham = vcat(ham, vcat(diffs .^ k))
        end
    elseif diffs_power < 0
        for k = 1:abs(diffs_power)
            ham = vcat(ham, vcat(diffs .^ -k))
        end
    end

    # Trigonometric state differences basis
    if trig_state_diffs > 0
        for k = 1:trig_state_diffs
            ham = vcat(ham, vcat(sin.(diffs) .^ k), vcat(cos.(diffs) .^ k))
        end
    elseif trig_state_diffs < 0
        for k = 1:abs(trig_state_diffs)
            ham = vcat(ham, vcat(sin.(diffs) .^ -k), vcat(cos.(diffs) .^ -k))
        end
    end

    # exponential state differences basis
    if exp_diff > 0
        for k = 1:exp_diff
            ham = vcat(ham, vcat(exp.(diffs) .^ k))
        end
    elseif exp_diff < 0
        for k = 1:abs(exp_diff)
            ham = vcat(ham, vcat(exp.(diffs) .^ -k))
        end
    end

    ham = sum(collect(a .* ham))
    return ham

end

In [ ]:

"""
returns the number of required parameters taking into account many types of basis functions
"""
function calculate_nparams(nd, polyorder, trig_wave_num, diffs_power, trig_state_diffs, exp_diff)
    # binomial used to get the combination of polynomials till the highest order without repeat, e.g nparam = 34 for 3rd order, with z = q,p each of 2 dims
    # nd: total number of dims of all variable states
    nparam = binomial(nd + polyorder, polyorder) - 1

    if trig_wave_num > 0
        # first 2 in the product formula b/c the trig basis are sin and cos i.e. two basis functions
        nparam += 2 * trig_wave_num * nd
    end

    if abs(diffs_power) > 0
        # diffs power is the max power of the difference of states in the library of basis functions
        nparam += abs(diffs_power) * nd * (nd-1)
    end

    if abs(trig_state_diffs) > 0 
        # we add this b/c we also want to get the powers of sin and cos of the difference of states in the function library
        nparam += 2 * abs(trig_state_diffs) * nd * (nd-1)
    end

    if abs(exp_diff) > 0
        # diffs power is the max power of the difference of states in the library of basis functions
        nparam += abs(exp_diff) * nd * (nd-1)
    end

    return nparam
end

In [ ]:
" returns a function that can build the gradient of the hamiltonian "
function ΔH_func_builder_two(d, polyorder, trig_wave_num, diffs_power, trig_state_diffs, exp_diff)
    # nd is the total number of dimensions of all the states, e.g. if q,p each of 3 dims, that is 6 dims in total
    nd = 2d
    
    # binomial used to get the combination of variables till the highest order without repeat, nparam = 34 for 3rd order, with z = q,p each of 2 dims
    nparam = calculate_nparams(nd, polyorder, trig_wave_num, diffs_power, trig_state_diffs, exp_diff)

    # symbolic variables
    @variables a[1:nparam]
    @variables q[1:d]
    @variables p[1:d]
    z = vcat(q,p)
    Dz = Differential.(z)
    
    # make a basis library
    ham = hamiltonian_two(z, a, polyorder, trig_wave_num, diffs_power, trig_state_diffs, exp_diff)
    
    # gives derivative of the hamiltonian, but not the skew-symmetric true one
    f = [expand_derivatives(dz(ham)) for dz in Dz]

    # line below makes the vector into a hamiltonian vector field by multiplying with the skew-symmetric matrix
    ∇H = vcat(f[d+1:2d], -f[1:d])

    # builds a function that calculates Hamiltonian gradient and converts the function to a native Julia function
    ∇H_eval = @RuntimeGeneratedFunction(Symbolics.inject_registered_module_functions(build_function(∇H, z, a)[2]))
    
    return ∇H_eval

end


In [ ]:

" returns a function that can build the gradient of the hamiltonian "
function hamilGrad_func_builder(d, polyorder, trig_wave_num, diffs_power, trig_state_diffs)
    # nd is the total number of dimensions of all the states, e.g. if q,p each of 3 dims, that is 6 dims in total
    nd = 2d
    # binomial used to get the combination of variables till the highest order without repeat, nparam = 34 for 3rd order, with z = q,p each of 2 dims
    nparam = calculate_nparams(nd, polyorder, trig_wave_num, diffs_power, trig_state_diffs)

    # symbolic variables
    @variables a[1:nparam]
    @variables q[1:d]
    @variables p[1:d]
    z = vcat(q,p)

    # usesine: whether to add trig basis or not
    if trig_wave_num > 0

        # gives derivative of the hamiltonian, but not the skew-symmetric true one
        Dz = Differential.(z)
        ∇H_add_trig = [expand_derivatives(dz(hamil_trig(z, a, polyorder, trig_wave_num))) for dz in Dz]

        # line below makes the vector into a hamiltonian vector field by multiplying with the skew-symmetric matrix
        ∇H_trig = vcat(∇H_add_trig[d+1:2d], -∇H_add_trig[1:d])

        # builds a function that calculates Hamiltonian gradient and converts the function to a native Julia function
        ∇H_eval = @RuntimeGeneratedFunction(Symbolics.inject_registered_module_functions(build_function(∇H_trig, z, a)[2]))

        return ∇H_eval

    else

        # gives derivative of the hamiltonian, but not the skew-symmetric true one
        Dz = Differential.(z)
        f = [expand_derivatives(dz(hamiltonian(z, a, polyorder))) for dz in Dz]

        f = replace(f, :(ifelse(signbit($(Expr(:quote, abs(x-y)))),-1,1)), :(abs(x-y)))

        # line below makes the vector into a hamiltonian by multiplying with the skew-symmetric matrix
        ∇H = vcat(f[d+1:2d], -f[1:d])

        # builds a function that calculates Hamiltonian gradient and converts the function to a native Julia function
        ∇H_eval = @RuntimeGeneratedFunction(Symbolics.inject_registered_module_functions(build_function(∇H, z, a)[2]))
        
        return ∇H_eval

    end

end

#### TESTING TIME ####

In [ ]:
# nd: total dims of all variables i.e p,q
nd = 4
# since we always have q and p, i.e 2 variables only, d will always be nd/2
d = div(nd, 2)

" trig_wave_num can be adjusted if higher frequency arguments expected "
trig_wave_num = 0

# highest order of polynomial library function
polyorder = 1

# states difference power
diffs_power = 0

# trig state difference power
trig_state_diffs = 0

# exponential state difference power
exp_diff = 1

"binomial used to get the combination of variables till the highest 
order without repeat, e.g with usesine= false, nparam = 34 for 3rd 
order, with z = q,p each of 2 dims"

nparam = calculate_nparams(nd, polyorder, trig_wave_num, diffs_power, trig_state_diffs, exp_diff)
println(nparam)

In [ ]:
# builds a function that calculates Hamiltonian gradient and converts the function to a native Julia function
∇H_eval = ΔH_func_builder_two(nd, polyorder, trig_wave_num, diffs_power, trig_state_diffs, exp_diff)

In [ ]:
# wrapper function for generalized SINDY hamiltonian gradient
function hamilGradient_general!(out, z, a::AbstractVector{T}, t) where T
    ∇H_eval(out, z, a)
    return out
end

In [ ]:
# 2D system with 4 variables [q₁, q₂, p₁, p₂] where q₂ = 0 and p₂ = 0
nd = 4

# 2 dims each of p and q gives 2*d = 4 variables
out = zeros(nd)

# let (a) be a vector of zeros initially of length 34 (b/c 34 is number of poly combinations for 2 variables, with 2 dims of highest order 3)

##################### NOTE: IN ACTUAL SCRIPT WE INITIALIZE THIS TO ZERO TO ALLOW BETTER OPTIMIZATION
a = ones(nparam)

x₀ = [2, 0, 0, 0]

t = 0
    

In [ ]:
hamilGradient_general!(out, x₀, a, 0)

#### New system for coefficients and basis ####

In [3]:
function get_z_vector(dims)
    @variables q[1:dims]
    @variables p[1:dims]
    z = vcat(q,p)
    return z
end

get_z_vector (generic function with 1 method)

In [4]:
# make combinations of bases of just the order that is given 
# e.g order = 2 will give just the bases whose powers sum to 2
function poly_combos(z, order, inds...)
    if order == 0
        return Num[1]
    elseif order == length(inds)
        return [_prod([z[i] for i in inds]...)]
    else
        start_ind = length(inds) == 0 ? 1 : inds[end]
        return vcat([poly_combos(z, order, inds..., j) for j in start_ind:length(z)]...)
    end
end

# gives all bases monomials up to a certain order
function primal_monomial_basis(z, order::Int)
    return Vector{Symbolics.Num}(vcat([poly_combos(z, i) for i in 1:order]...))
end

# calculates coefficient bases up to a certain order
# mostly for use with trigonometric functions example sin(k*z),
# where k is the coefficient
function primal_coeff_basis(z, max_coeff::Int)
    return Vector{Symbolics.Num}(vcat([k .* z for k in 1:max_coeff]...))
end

# calculates +,-,*,/ between states as a new basis
# the return output is a set to avoid duplicates
function primal_operator_basis(z, operator)
    return Vector{Symbolics.Num}([operator(z[i], z[j]) for i in 1:length(z)-1 for j in i+1:length(z)] ∪ [operator(z[j], z[i]) for i in 1:length(z)-1 for j in i+1:length(z)])
end

# calculates power of states as a new basis
function primal_power_basis(z, max_power::Int)
    if max_power > 0
        return Vector{Symbolics.Num}(vcat([z.^i for i in 1:max_power]...))
    elseif max_power < 0
        return Vector{Symbolics.Num}(vcat([z.^-i for i in 1:abs(max_power)]...))
    end
end

primal_power_basis (generic function with 1 method)

In [5]:
function polynomial_basis(z::Vector{Symbolics.Num} = get_z_vector(2); polyorder::Int = 0, operator=nothing, max_coeff::Int = 0)
    primes = primal_monomial_basis(z, polyorder)
    primes = vcat(primes, primal_coeff_basis(z, max_coeff))
    if operator !== nothing
        primes = vcat(primes, primal_operator_basis(z, operator))
    end
    return primes
end

function trigonometric_basis(z::Vector{Symbolics.Num} = get_z_vector(2); polyorder::Int = 0, operator=nothing, max_coeff::Int = 0)
    primes = polynomial_basis(z, polyorder = polyorder, operator = operator, max_coeff = max_coeff)
    return vcat(sin.(primes), cos.(primes))
end

function exponential_basis(z::Vector{Symbolics.Num} = get_z_vector(2); polyorder::Int = 0, operator=nothing, max_coeff::Int = 0)
    primes = polynomial_basis(z, polyorder = polyorder, operator = operator, max_coeff = max_coeff)
    return exp.(primes)
end

function logarithmic_basis(z::Vector{Symbolics.Num} = get_z_vector(2); polyorder::Int = 0, operator=nothing, max_coeff::Int = 0)
    primes = polynomial_basis(z, polyorder = polyorder, operator = operator, max_coeff = max_coeff)
    return log.(abs.(primes))
end

function mixed_states_basis(basis::Vector{Symbolics.Num}...)
    mixed_states = Tuple(basis)
    
    ham = Vector{Symbolics.Num}()
    for i in eachindex(mixed_states)
        for j in i+1:lastindex(mixed_states)
            ham = vcat(ham, [mixed_states[i][k] * mixed_states[j][l] for k in 1:length(mixed_states[i]) for l in 1:length(mixed_states[j])])
        end
    end
    
    return Vector{Symbolics.Num}(ham)
end

mixed_states_basis (generic function with 1 method)

In [6]:
# Returns the number of required coefficients for the bases
function get_numCoeffs(basis::Vector{Symbolics.Num})
    return length(basis)
end

get_numCoeffs (generic function with 1 method)

In [7]:
# gets a vector of combinations of basis
function get_basis_set(bases::Vector{Symbolics.Num}...)
    # gets a vector of combinations of basis
    basis = vcat(bases...)
    
    # removes duplicates
    basis = Vector{Symbolics.Num}(collect(unique(basis)))

    return basis
end

get_basis_set (generic function with 1 method)

In [8]:
function ΔH_func_builder(d::Int, z::Vector{Symbolics.Num} = get_z_vector(d), bases::Vector{Symbolics.Num}...) 
    # nd is the total number of dimensions of all the states, e.g. if q,p each of 3 dims, that is 6 dims in total
    nd = 2d
    Dz = Differential.(z)
    
    # collects and sums combinations of basis and coefficients"
    basis = get_basis_set(bases...)
   
    # gets number of terms in the basis
    @variables a[1:get_numCoeffs(basis)]
    
    # collect and sum combinations of basis and coefficients
    ham = sum(collect(a .* basis))
    
    # gives derivative of the hamiltonian, but not the skew-symmetric true one
    f = [expand_derivatives(dz(ham)) for dz in Dz]
    
    # line below makes the vector into a hamiltonian vector field by multiplying with the skew-symmetric matrix
    ∇H = vcat(f[d+1:2d], -f[1:d])
    
    # builds a function that calculates Hamiltonian gradient and converts the function to a native Julia function
    ∇H_eval = @RuntimeGeneratedFunction(Symbolics.inject_registered_module_functions(build_function(∇H, z, a)[2]))
    
    return ∇H_eval
end

ΔH_func_builder (generic function with 2 methods)

In [9]:
d = 1
z = get_z_vector(d)
z = primal_operator_basis(z, -)
polynomial = polynomial_basis(z, polyorder=2)
trigonometric  = trigonometric_basis(z, polyorder = 1, operator = /)
logarithmic = logarithmic_basis(z, polyorder = 0, operator = -)
exponential = exponential_basis(z, polyorder=1, operator = +, max_coeff=1)
mixed_basis = mixed_states_basis(trigonometric, polynomial)
prime_mono = primal_monomial_basis(z, d)

nd = 2d
Dz = Differential.(z)

# collects and sums combinations of basis and coefficients"
basis = get_basis_set(polynomial)

# gets number of terms in the basis
@variables a[1:get_numCoeffs(basis)]

# collect and sum combinations of basis and coefficients
ham = sum(collect(a .* basis))

# gives derivative of the hamiltonian, but not the skew-symmetric true one
f = [expand_derivatives(dz(ham)) for dz in Dz]

# # line below makes the vector into a hamiltonian vector field by multiplying with the skew-symmetric matrix
# ∇H = vcat(f[d+1:2d], -f[1:d])

2-element Vector{Num}:
 (p[1] - q[1])*a[4] + 2(q[1] - p[1])*a[3] + a[1]
 (q[1] - p[1])*a[4] + 2(p[1] - q[1])*a[5] + a[2]

In [10]:
d = 2
z = get_z_vector(d)
z = primal_operator_basis(z, -)
polynomial = polynomial_basis(z, polyorder=3)
trigonometric  = trigonometric_basis(z, polyorder = 1, operator = /)
logarithmic = logarithmic_basis(z, polyorder = 0, operator = -)
exponential = exponential_basis(z, polyorder=1, operator = +, max_coeff=1)
mixed_basis = mixed_states_basis(trigonometric, polynomial)

out = ΔH_func_builder(d, z,
    polynomial, trigonometric
    ) 

RuntimeGeneratedFunction(#=in Main=#, #=using Main=#, :((ˍ₋out, ˍ₋arg1, a)->begin
          #= C:\Users\nigel\.julia\packages\SymbolicUtils\H684H\src\code.jl:350 =#
          #= C:\Users\nigel\.julia\packages\SymbolicUtils\H684H\src\code.jl:351 =#
          #= C:\Users\nigel\.julia\packages\SymbolicUtils\H684H\src\code.jl:352 =#
          begin
              begin
                  #= C:\Users\nigel\.julia\packages\Symbolics\3jLt1\src\build_function.jl:520 =#
                  #= C:\Users\nigel\.julia\packages\SymbolicUtils\H684H\src\code.jl:399 =# @inbounds begin
                          #= C:\Users\nigel\.julia\packages\SymbolicUtils\H684H\src\code.jl:395 =#
                          ˍ₋out[1] = (+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((+)((

In [10]:
z = get_z_vector(4)
polynomial = polynomial_basis(z, polyorder=2)

z_diff = primal_operator_basis(z, -)
exponential_diff  = exponential_basis(z_diff, polyorder=1)
z_power = primal_power_basis(exponential_diff, 2)
basis = get_basis_set(polynomial, z_power)
# basis = get_basis_set(polynomial)
# basis = get_basis_set(exponential_diff)
@variables a[1:get_numCoeffs(basis)]
nd = 8
Dz = Differential.(z)
# collect and sum combinations of basis and coefficients
ham = sum(collect(a .* basis))

# # gives derivative of the hamiltonian, but not the skew-symmetric true one
# f = [expand_derivatives(dz(ham)) for dz in Dz]

# # # line below makes the vector into a hamiltonian vector field by multiplying with the skew-symmetric matrix
# ∇H = vcat(f[d+1:2d], -f[1:d])

(exp(q[1] - p[1])^2)*a[104] + (exp(q[2] - p[1])^2)*a[110] + (exp(p[3] - q[1])^2)*a[134] + (exp(q[4] - p[1])^2)*a[119] + (exp(q[3] - p[3])^2)*a[117] + (exp(q[3] - p[4])^2)*a[118] + (exp(q[4] - p[2])^2)*a[120] + (exp(q[4] - p[4])^2)*a[122] + (exp(p[1] - p[3])^2)*a[124] + (exp(q[4] - q[3])^2)*a[142] + (q[3]^2)*a[24] + exp(p[2] - p[1])*a[95] + exp(p[1] - q[2])*a[82] + exp(q[3] - p[3])*a[61] + exp(p[3] - q[4])*a[93] + exp(q[1] - p[4])*a[51] + exp(q[3] - q[4])*a[58] + exp(p[4] - q[3])*a[90] + (exp(p[3] - p[2])^2)*a[154] + (exp(p[1] - q[3])^2)*a[143] + (exp(p[4] - q[4])^2)*a[150] + exp(p[4] - p[2])*a[99] + exp(p[1] - p[4])*a[69] + exp(q[1] - p[2])*a[49] + exp(q[2] - p[4])*a[57] + exp(q[4] - p[3])*a[65] + (exp(p[1] - p[4])^2)*a[125] + (exp(p[4] - q[2])^2)*a[141] + exp(p[2] - q[2])*a[83] + exp(q[2] - q[1])*a[73] + exp(q[4] - q[1])*a[75] + (exp(q[3] - p[2])^2)*a[116] + exp(p[3] - q[2])*a[84] + exp(q[4] - q[2])*a[81] + (exp(q[3] - q[2])^2)*a[136] + (exp(p[4] - p[1])^2)*a[153] + (q[2]^2)*a[17] + (

In [12]:
get_numCoeffs(basis)

156

In [ ]:
z = get_z_vector(2)
polynomial = polynomial_basis(z, polyorder=2)
z_diff = primal_operator_basis(z, -)
log_diff  = logarithmic_basis(z_diff, polyorder=1)
z_log_power = primal_power_basis(log_diff, 1)
mixed_basis = mixed_states_basis(polynomial, z_log_power)
basis = get_basis_set(mixed_basis)
@variables a[1:get_numCoeffs(basis)]
# collect and sum combinations of basis and coefficients
ham = collect(a .* basis)

In [29]:
(signbit.(z))

4-element Vector{Num}:
 signbit(q[1])
 signbit(q[2])
 signbit(p[1])
 signbit(p[2])

In [38]:
d = 2
z = get_z_vector(d)
signmap(z) = ifelse.(signbit.(z),-1,1)
log_diff  = signmap.(z).*logarithmic_basis(z, polyorder=1)
basis = get_basis_set(log_diff)
Dz = Differential.(z)

f = simplify(f)
# # gives derivative of the hamiltonian, but not the skew-symmetric true one
f = [expand_derivatives(dz(sum(basis))) for dz in Dz]


4-element Vector{Num}:
 (ifelse(signbit(q[1]), -1, 1)^2) / abs(q[1]) + ifelse(signbit(q[1]), 0, 0)*log(abs(q[1]))
 (ifelse(signbit(q[2]), -1, 1)^2) / abs(q[2]) + ifelse(signbit(q[2]), 0, 0)*log(abs(q[2]))
 (ifelse(signbit(p[1]), -1, 1)^2) / abs(p[1]) + ifelse(signbit(p[1]), 0, 0)*log(abs(p[1]))
 (ifelse(signbit(p[2]), -1, 1)^2) / abs(p[2]) + ifelse(signbit(p[2]), 0, 0)*log(abs(p[2]))

In [21]:
Int(false)*2 - 1

-1

In [40]:
d = 2
z = get_z_vector(d)
polynomial = polynomial_basis(z, polyorder=2)
z_diff = primal_operator_basis(z, -)
log_diff  = logarithmic_basis(z_diff, polyorder=1)
z_log_power = primal_power_basis(log_diff, 1)
mixed_basis = mixed_states_basis(polynomial, z_log_power)
basis = get_basis_set(mixed_basis)
@variables a[1:get_numCoeffs(basis)]

collect(a .* basis)
# collect and sum combinations of basis and coefficients
ham = sum(collect(a .* basis))

Dz = Differential.(z)

# # gives derivative of the hamiltonian, but not the skew-symmetric true one
f = [expand_derivatives(dz(ham)) for dz in Dz]

f = simplify(f)

# # line below makes the vector into a hamiltonian vector field by multiplying with the skew-symmetric matrix
∇H = vcat(f[d+1:2d], - f[1:d])

4-element Vector{Num}:
  ((q[1]^2)*a[58]*ifelse(signbit(p[1] - q[2]), -1, 1)) / abs(p[1] - q[2]) + ((p[1]^2)*a[138]*ifelse(signbit(p[1] - p[2]), -1, 1)) / abs(p[1] - p[2]) + ((p[2]^2)*a[162]*ifelse(signbit(p[1] - p[2]), -1, 1)) / abs(p[1] - p[2]) + (a[6]*q[1]*ifelse(signbit(p[1] - p[2]), -1, 1)) / abs(p[1] - p[2]) + ((p[2]^2)*a[164]*ifelse(signbit(p[1] - q[1]), -1, 1)) / abs(p[1] - q[1]) + ((p[1]^2)*a[142]*ifelse(signbit(p[1] - q[2]), -1, 1)) / abs(p[1] - q[2]) + ((q[1]^2)*a[54]*ifelse(signbit(p[1] - p[2]), -1, 1)) / abs(p[1] - p[2]) + ((q[2]^2)*a[102]*ifelse(signbit(p[1] - p[2]), -1, 1)) / abs(p[1] - p[2]) + ((q[2]^2)*a[106]*ifelse(signbit(p[1] - q[2]), -1, 1)) / abs(p[1] - q[2]) + (a[22]*q[2]*ifelse(signbit(p[1] - q[2]), -1, 1)) / abs(p[1] - q[2]) + (a[30]*p[1]*ifelse(signbit(p[1] - p[2]), -1, 1)) / abs(p[1] - p[2]) + ((q[1]^2)*a[56]*ifelse(signbit(p[1] - q[1]), -1, 1)) / abs(p[1] - q[1]) + ((p[1]^2)*a[140]*ifelse(signbit(p[1] - q[1]), -1, 1)) / abs(p[1] - q[1]) + (a[34]*p[1]*ifelse(

In [22]:
collect(a .* basis)

168-element Vector{Num}:
       log(abs(q[1] - q[2]))*a[1]*q[1]
       log(abs(q[1] - p[1]))*a[2]*q[1]
       log(abs(q[1] - p[2]))*a[3]*q[1]
       log(abs(q[2] - p[1]))*a[4]*q[1]
       log(abs(q[2] - p[2]))*a[5]*q[1]
       log(abs(p[1] - p[2]))*a[6]*q[1]
       log(abs(q[2] - q[1]))*a[7]*q[1]
       log(abs(p[1] - q[1]))*a[8]*q[1]
       log(abs(p[2] - q[1]))*a[9]*q[1]
      log(abs(p[1] - q[2]))*a[10]*q[1]
                                     ⋮
 (p[2]^2)*log(abs(q[2] - p[1]))*a[160]
 (p[2]^2)*log(abs(q[2] - p[2]))*a[161]
 (p[2]^2)*log(abs(p[1] - p[2]))*a[162]
 (p[2]^2)*log(abs(q[2] - q[1]))*a[163]
 (p[2]^2)*log(abs(p[1] - q[1]))*a[164]
 (p[2]^2)*log(abs(p[2] - q[1]))*a[165]
 (p[2]^2)*log(abs(p[1] - q[2]))*a[166]
 (p[2]^2)*log(abs(p[2] - q[2]))*a[167]
 (p[2]^2)*log(abs(p[2] - p[1]))*a[168]

In [13]:
using Symbolics

@variables p₁ q₁ q₂
f = q₁^2 * log(abs(-q₂ + p₁))
D = Differential(p₁)
df_dp1 = expand_derivatives(D(f))

df_dp1_fn = build_function(df_dp1, [p₁, q₁, q₂])
    


:(function (ˍ₋arg1,)
      #= C:\Users\nigel\.julia\packages\SymbolicUtils\H684H\src\code.jl:350 =#
      #= C:\Users\nigel\.julia\packages\SymbolicUtils\H684H\src\code.jl:351 =#
      #= C:\Users\nigel\.julia\packages\SymbolicUtils\H684H\src\code.jl:352 =#
      begin
          (/)((*)((^)(ˍ₋arg1[2], 2), if (signbit)((+)(ˍ₋arg1[1], (*)(-1, ˍ₋arg1[3])))
                      -1
                  else
                      1
                  end), (abs)((+)(ˍ₋arg1[1], (*)(-1, ˍ₋arg1[3]))))
      end
  end)